version: "3.7"
services:
  flask:
    build: ./flask_docker
    container_name: flask_docker
    network_mode: host
    ports:
      - "8000:8000"
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"