version: "3.7"
services:
  flask:
    build: ./flask_docker
    container_name: flask_docker
    restart: always
    environment:
    - APP_NAME=app
    env_file:
    - .env
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"